#!/bin/bash

#SBATCH --account=ostein_1459
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --gpus-per-task=a40:1
#SBATCH --mem=16GB
#SBATCH --time=6:00:00
#SBATCH --job-name=render_opt_iters_vis
#SBATCH --output=render_opt_iters_vis.out

module purge
module load gcc libxkbcommon libxi mesa

eval "$(conda shell.bash hook)"
conda activate sieves-kaolin

python /home1/jaeyoonc/sieves-kaolin/figures/render_opt_iters_vis.py \
       /home1/jaeyoonc/sieves-kaolin/scripts/67223_vs_591211.json