#!/bin/bash

#SBATCH --account=ostein_1459
#SBATCH --partition=main
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --mem=4GB
#SBATCH --time=6:00:00
#SBATCH --job-name=runtime_analysis
#SBATCH --output=runtime_analysis.out

module purge

eval "$(conda shell.bash hook)"
conda activate sieves-kaolin

python runtime_analysis.py 62526_cut_vs_62526 mesh_A_pso_iters ../scripts/62526_cut_vs_62526_mesh_A_pso_iters_jobs.txt
python runtime_analysis.py 62526_cut_vs_62526 mesh_A_opt_num_posns ../scripts/62526_cut_vs_62526_mesh_A_opt_num_posns_jobs.txt
python runtime_analysis.py 62526_cut_vs_62526 mesh_B_opt_iters ../scripts/62526_cut_vs_62526_mesh_B_opt_iters_jobs.txt
python runtime_analysis.py 62526_cut_vs_62526 mesh_B_opt_num_posns ../scripts/62526_cut_vs_62526_mesh_B_opt_num_posns_jobs.txt
