#!/bin/bash

#SBATCH --account=ostein_1459
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --gpus-per-task=a40:1
#SBATCH --mem=4GB
#SBATCH --time=1:00:00
#SBATCH --job-name=runtime_analysis_of_mesh_count_and_complexity
#SBATCH --output=runtime_analysis_of_mesh_count_and_complexity.out

module purge
module load gcc libxkbcommon libxi mesa

eval "$(conda shell.bash hook)"
conda activate sieves-kaolin

python runtime_analysis_of_mesh_count_and_complexity.py runtime_analysis_of_mesh_count_and_complexity_result_names.txt
