#!/bin/bash

#SBATCH --account=ostein_1459
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --gpus-per-task=a40:1
#SBATCH --mem=16GB
#SBATCH --time=24:00:00
#SBATCH --job-name=32770_vs_30_random_B_meshes
#SBATCH --output=32770_vs_30_random_B_meshes.out

module purge

eval "$(conda shell.bash hook)"
conda activate sieves-kaolin

python /home1/jaeyoonc/sieves-kaolin/scripts/generate_sieve.py \
       32770_vs_30_random_B_meshes.json \
       /home1/jaeyoonc/sieves-kaolin/results/32770_vs_30_random_B_meshes