#!/bin/bash

#SBATCH --account=ostein_1459
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --gpus-per-task=a40:1
#SBATCH --mem=16GB
#SBATCH --time=6:00:00
#SBATCH --job-name=62860_vs_cube_hole_filling_off
#SBATCH --output=62860_vs_cube_hole_filling_off.out

module purge

eval "$(conda shell.bash hook)"
conda activate sieves-kaolin

python /home1/jaeyoonc/sieves-kaolin/scripts/generate_sieve.py \
       /home1/jaeyoonc/sieves-kaolin/scripts/62860_vs_cube_hole_filling_off.json \
       /home1/jaeyoonc/sieves-kaolin/results/62860_vs_cube_hole_filling_off
